import { StateGraph, type GraphNode, START, END, StateSchema } from "@langchain/langgraph";
import { z } from "zod";
import { geminiModel, mistralAIModel, cohereModel } from "./model.ai.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
    // winner: z.enum(["solution_1", "solution_2", "tie"]).default("tie")
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistralResponse, cohereResponse] = await Promise.all([
    mistralAIModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text,
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judge = createAgent({
    model: geminiModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
        // winner: z.enum(["solution_1", "solution_2", "tie"])
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by two different AI models. Please provide a score between 0 and 10 for each solution, along with your reasoning.`,
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(
        `Problem: ${problem}\n\nSolution 1: ${solution_1}\n\nSolution 2: ${solution_2}\n\nPlease evaluate the solutions and provide scores and reasoning for each.`,
      ),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
    // winner
  } = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
      // winner
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solution_node", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solution_node")
  .addEdge("solution_node", "judge_node")
  .addEdge("judge_node", END)
  .compile();

export default async function (problem: string){
    const result = await graph.invoke({
        problem: problem
    })

    return result;
}


